import { ingredientSupplierAdminFixture } from "./ingredientSupplierAdminFixtures";
import type { DishRecipeAdminState } from "./dishRecipeAdminDomain";

export const dishRecipeAdminFixture: DishRecipeAdminState = {
  dishes: [
    {
      dishId: "dish-pumpkin-soup",
      dishName: "Pumpkin soup",
      dishCategory: "Soup",
      status: "ACTIVE",
      displayOrder: 10,
      operationalNotes: "Reviewed recipe foundation fixture.",
      requiresNeedGeneration: true,
      statusChanges: [
        {
          dishStatusChangeId: "dish-pumpkin-soup-status-1",
          dishId: "dish-pumpkin-soup",
          beforeStatus: "DRAFT",
          afterStatus: "ACTIVE",
          actorId: "admin-lan",
          at: "2026-07-10T01:00:00.000Z",
          reason: "Approved for menu reference",
        },
      ],
      masterDataChanges: [
        {
          dishMasterDataChangeId: "dish-pumpkin-soup-change-1",
          dishId: "dish-pumpkin-soup",
          changeType: "DishActivated",
          actorId: "admin-lan",
          at: "2026-07-10T01:00:00.000Z",
          reason: "Approved for menu reference",
          before: "DRAFT",
          after: "ACTIVE",
        },
      ],
    },
    {
      dishId: "dish-steamed-rice",
      dishName: "Steamed rice",
      dishCategory: "Staple",
      status: "ACTIVE",
      displayOrder: 20,
      requiresNeedGeneration: true,
      statusChanges: [],
      masterDataChanges: [],
    },
    {
      dishId: "dish-fried-fish",
      dishName: "Fried fish",
      dishCategory: "Main",
      status: "ACTIVE",
      displayOrder: 30,
      requiresNeedGeneration: true,
      statusChanges: [],
      masterDataChanges: [],
    },
    {
      dishId: "dish-legacy-soup",
      dishName: "Legacy pantry soup",
      dishCategory: "Soup",
      status: "INACTIVE",
      displayOrder: 90,
      requiresNeedGeneration: true,
      statusChanges: [
        {
          dishStatusChangeId: "dish-legacy-soup-status-1",
          dishId: "dish-legacy-soup",
          beforeStatus: "ACTIVE",
          afterStatus: "INACTIVE",
          actorId: "admin-lan",
          at: "2026-07-11T01:00:00.000Z",
          reason: "Retired menu identity",
        },
      ],
      masterDataChanges: [],
    },
  ],
  recipes: [
    {
      recipeId: "recipe-pumpkin-soup",
      dishId: "dish-pumpkin-soup",
      recipeName: "Pumpkin soup recipe",
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:00:00.000Z",
    },
    {
      recipeId: "recipe-steamed-rice",
      dishId: "dish-steamed-rice",
      recipeName: "Steamed rice recipe",
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:00:00.000Z",
    },
    {
      recipeId: "recipe-fried-fish",
      dishId: "dish-fried-fish",
      recipeName: "Fried fish recipe",
      createdBy: "admin-lan",
      createdAt: "2026-07-13T02:00:00.000Z",
    },
    {
      recipeId: "recipe-legacy-soup",
      dishId: "dish-legacy-soup",
      recipeName: "Legacy pantry soup recipe",
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:00:00.000Z",
    },
  ],
  recipeVersions: [
    {
      recipeVersionId: "recipe-pumpkin-v1",
      recipeId: "recipe-pumpkin-soup",
      versionNumber: 1,
      status: "LOCKED",
      requiredSchoolTypeIds: [],
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:10:00.000Z",
      validatedBy: "admin-lan",
      validatedAt: "2026-07-10T03:00:00.000Z",
      releasedBy: "admin-lan",
      releasedAt: "2026-07-10T04:00:00.000Z",
    },
    {
      recipeVersionId: "recipe-pumpkin-v2",
      recipeId: "recipe-pumpkin-soup",
      versionNumber: 2,
      status: "DRAFT",
      basedOnRecipeVersionId: "recipe-pumpkin-v1",
      requiredSchoolTypeIds: ["school-type-primary"],
      createdBy: "admin-lan",
      createdAt: "2026-07-14T02:00:00.000Z",
    },
    {
      recipeVersionId: "recipe-rice-v1",
      recipeId: "recipe-steamed-rice",
      versionNumber: 1,
      status: "RELEASED_FOR_PLANNING",
      requiredSchoolTypeIds: [],
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:00:00.000Z",
      validatedBy: "admin-lan",
      validatedAt: "2026-07-10T03:00:00.000Z",
      releasedBy: "admin-lan",
      releasedAt: "2026-07-10T04:00:00.000Z",
    },
    {
      recipeVersionId: "recipe-fish-v1",
      recipeId: "recipe-fried-fish",
      versionNumber: 1,
      status: "DRAFT",
      requiredSchoolTypeIds: ["school-type-primary"],
      createdBy: "admin-lan",
      createdAt: "2026-07-13T02:00:00.000Z",
    },
    {
      recipeVersionId: "recipe-legacy-v1",
      recipeId: "recipe-legacy-soup",
      versionNumber: 1,
      status: "VALIDATED",
      requiredSchoolTypeIds: [],
      createdBy: "admin-lan",
      createdAt: "2026-07-10T02:00:00.000Z",
      validatedBy: "admin-lan",
      validatedAt: "2026-07-11T02:00:00.000Z",
    },
  ],
  recipeLocks: [
    {
      recipeLockId: "recipe-pumpkin-v1-lock-1",
      recipeVersionId: "recipe-pumpkin-v1",
      status: "LOCKED",
      actorId: "admin-lan",
      at: "2026-07-10T05:00:00.000Z",
      reason: "Preserve released Planning basis",
    },
  ],
  recipeLines: [
    {
      recipeLineId: "pumpkin-v1-rice",
      recipeVersionId: "recipe-pumpkin-v1",
      ingredientId: "ingredient-rice",
      quantity: 0.08,
      unit: "kg",
    },
    {
      recipeLineId: "pumpkin-v1-old-oil",
      recipeVersionId: "recipe-pumpkin-v1",
      ingredientId: "ingredient-old-oil",
      quantity: 0.01,
      unit: "liter",
      inactiveIngredientOverrideEvidence:
        "Historical locked reference; unavailable for new recipes.",
    },
    {
      recipeLineId: "pumpkin-v2-rice",
      recipeVersionId: "recipe-pumpkin-v2",
      ingredientId: "ingredient-rice",
      quantity: 0.09,
      unit: "kg",
    },
    {
      recipeLineId: "pumpkin-v2-onion",
      recipeVersionId: "recipe-pumpkin-v2",
      ingredientId: "ingredient-spring-onion",
      quantity: 0.2,
      unit: "bundle",
      notes: "Approved conversion exists; operator review remains visible.",
    },
    {
      recipeLineId: "rice-v1-rice",
      recipeVersionId: "recipe-rice-v1",
      ingredientId: "ingredient-rice",
      quantity: 0.12,
      unit: "kg",
    },
    {
      recipeLineId: "fish-v1-missing",
      recipeVersionId: "recipe-fish-v1",
      ingredientId: "ingredient-not-found",
      quantity: 0,
      unit: "kg",
    },
    {
      recipeLineId: "legacy-v1-rice",
      recipeVersionId: "recipe-legacy-v1",
      ingredientId: "ingredient-rice",
      quantity: 0.1,
      unit: "kg",
    },
  ],
  schoolTypeVariants: [
    {
      schoolTypeRecipeVariantId: "pumpkin-v2-primary-rice",
      recipeVersionId: "recipe-pumpkin-v2",
      schoolTypeId: "school-type-primary",
      recipeLineId: "pumpkin-v2-rice",
      quantity: 0.08,
      unit: "kg",
      reason: "Primary-school portion profile",
    },
  ],
  recipeChangeSets: [
    {
      recipeChangeSetId: "pumpkin-change-set-v2",
      recipeId: "recipe-pumpkin-soup",
      fromRecipeVersionId: "recipe-pumpkin-v1",
      toRecipeVersionId: "recipe-pumpkin-v2",
      status: "APPROVED",
      summary: "Replace legacy oil and adjust the base portion.",
      actorId: "admin-lan",
      at: "2026-07-14T02:00:00.000Z",
      reason: "Prepare a safe successor version",
      approvedBy: "admin-minh",
      approvedAt: "2026-07-14T03:00:00.000Z",
    },
  ],
  recipeReviewEvidence: [
    {
      recipeReviewEvidenceId: "pumpkin-change-set-v2-evidence-1",
      recipeChangeSetId: "pumpkin-change-set-v2",
      recipeVersionId: "recipe-pumpkin-v2",
      reviewScope: "ADMIN_RECIPE_MASTER_DATA",
      outcome: "APPROVED_FOR_RECIPE_RELEASE",
      actorId: "admin-minh",
      at: "2026-07-14T03:00:00.000Z",
      evidence:
        "BOM and school-type quantities reviewed against Admin references.",
      grantsQaApproval: false,
      grantsProductionApproval: false,
    },
  ],
  recipeMasterDataChanges: [
    {
      recipeMasterDataChangeId: "recipe-change-1",
      recipeId: "recipe-pumpkin-soup",
      recipeVersionId: "recipe-pumpkin-v2",
      changeType: "RecipeVersionCreated",
      actorId: "admin-lan",
      at: "2026-07-14T02:00:00.000Z",
      reason: "Correct the locked v1 through a successor version",
    },
    {
      recipeMasterDataChangeId: "recipe-change-2",
      recipeId: "recipe-pumpkin-soup",
      recipeVersionId: "recipe-pumpkin-v2",
      changeType: "RecipeChangeSetApproved",
      actorId: "admin-minh",
      at: "2026-07-14T03:00:00.000Z",
      reason: "Admin recipe master-data review complete",
    },
  ],
  ingredients: ingredientSupplierAdminFixture.ingredients,
  unitConversionRules: ingredientSupplierAdminFixture.unitConversionRules,
  releasedRecipeReferences: [
    {
      releasedRecipeReferenceId: "recipe-pumpkin-v1-release-1",
      dishId: "dish-pumpkin-soup",
      recipeId: "recipe-pumpkin-soup",
      recipeVersionId: "recipe-pumpkin-v1",
      releasedAt: "2026-07-10T04:00:00.000Z",
      releasedBy: "admin-lan",
      effect: "FUTURE_PLANNING_REFERENCE_ONLY",
    },
    {
      releasedRecipeReferenceId: "recipe-rice-v1-release-1",
      dishId: "dish-steamed-rice",
      recipeId: "recipe-steamed-rice",
      recipeVersionId: "recipe-rice-v1",
      releasedAt: "2026-07-10T04:00:00.000Z",
      releasedBy: "admin-lan",
      effect: "FUTURE_PLANNING_REFERENCE_ONLY",
    },
  ],
  downstreamRecipeUsage: [
    {
      usageId: "planning-run-0713-pumpkin-v1",
      recipeVersionId: "recipe-pumpkin-v1",
      domain: "PLANNING",
      referenceId: "planning-run-2026-07-13",
      recordedAt: "2026-07-13T04:00:00.000Z",
    },
    {
      usageId: "need-run-0713-pumpkin-v1",
      recipeVersionId: "recipe-pumpkin-v1",
      domain: "NEED_GENERATION",
      referenceId: "need-run-2026-07-13",
      recordedAt: "2026-07-13T05:00:00.000Z",
    },
  ],
};
