-- Stable business keys and exact numeric strings, never random IDs/times.
reset role;
select '02D_SEMANTICS='||jsonb_build_object(
 'commands',(select jsonb_agg(jsonb_build_object('scenario',RESULT_NAME,'success',RESULT_RESPONSE->'success','error',RESULT_RESPONSE->>'error_code','status',RESULT_RESPONSE->>'status','replayed',RESULT_RESPONSE->'replayed') order by RESULT_NAME) from RESULT_TABLE),
 'master_identities',(select jsonb_agg(jsonb_build_array(source_system,object_type,legacy_id,last_source_fingerprint) order by source_system,object_type,legacy_id) from atlas_legacy.master_data_mappings),
 'recipe_composition',(select jsonb_agg(jsonb_build_array(d.dish_code,st.school_type_code,i.ingredient_code,u.unit_code,rr.quantity_per_basis::text,rr.line_disposition,rv.recipe_version_status,rr.predecessor_recipe_line_revision_id is not null) order by d.dish_code,st.school_type_code,i.ingredient_code,rv.version_number,rr.line_disposition) from atlas_admin.recipe_line_revisions rr join atlas_admin.recipe_versions rv on rv.recipe_version_id=rr.recipe_version_id join atlas_admin.recipes r on r.recipe_id=rv.recipe_id join atlas_admin.dishes d on d.dish_id=r.dish_id join atlas_admin.school_types st on st.school_type_id=r.school_type_id join atlas_admin.ingredients i on i.ingredient_id=rr.ingredient_id join atlas_admin.units u on u.unit_id=rr.unit_id),
 'unit_provenance',(select jsonb_agg(jsonb_build_array(a.evidence_kind,a.source_system,a.snapshot_id,a.snapshot_checksum,a.legacy_recipe_line_id,a.source_fingerprint,i.ingredient_code,a.quantity_per_basis::text,s.unit_code,c.unit_code,a.predecessor_recipe_line_revision_id is not null) order by a.snapshot_id,a.legacy_recipe_line_id) from atlas_legacy.recipe_unit_adoption_evidence a join atlas_admin.ingredients i using(ingredient_id) join atlas_admin.units s on s.unit_id=a.source_unit_id join atlas_admin.units c on c.unit_id=a.corrected_unit_id),
 'po_snapshots',(select jsonb_agg(jsonb_build_array(r.service_date,s.supplier_code,p.purchase_order_status,r.revision_status,r.supplier_name_snapshot,r.delivery_location_snapshot,i.ingredient_code,u.unit_code,l.ordered_quantity::text,l.supplier_note_snapshot,l.school_breakdown_snapshot) order by r.service_date,s.supplier_code,i.ingredient_code,r.revision_number) from atlas_procurement.purchase_orders p join atlas_procurement.purchase_order_revisions r using(purchase_order_id) join atlas_procurement.purchase_order_line_revisions l using(purchase_order_revision_id) join atlas_admin.suppliers s using(supplier_id) join atlas_admin.ingredients i using(ingredient_id) join atlas_admin.units u using(unit_id) where r.revision_status='RELEASED_TO_SUPPLIER'),
 'receipt_counts',(select jsonb_agg(jsonb_build_array(command_name,outcome,n) order by command_name,outcome) from (select command_name,outcome,count(*) n from atlas_core.command_receipts group by command_name,outcome) counts),
 'pxk_snapshots',(select jsonb_agg(jsonb_build_array(r.service_date,s.school_code,d.location_code,r.release_status,r.school_name_snapshot,r.delivery_location_name_snapshot,r.delivery_address_snapshot,r.note,r.version,r.predecessor_release_id is not null,r.school_display_order_snapshot,r.document_issuer_name_snapshot,r.document_issuer_address_snapshot,i.ingredient_code,u.unit_code,l.quantity::text,l.ingredient_name_snapshot,l.unit_code_snapshot) order by r.service_date,s.school_code,d.location_code,r.version,i.ingredient_code) from atlas_dispatch.school_dispatch_releases r join atlas_dispatch.school_dispatch_release_lines l using(school_dispatch_release_id) join atlas_admin.schools s using(school_id) join atlas_admin.delivery_locations d using(delivery_location_id) join atlas_admin.ingredients i using(ingredient_id) join atlas_admin.units u using(unit_id)),
 'event_count',(select count(*) from atlas_audit.domain_events),
 'audit_count',(select count(*) from atlas_audit.audit_events)
)::text;
